sudo: required
services:
  - docker
before_install:
  - docker pull yglukhov/devel
script:
  - docker run -v "$(pwd):/project" -w /project yglukhov/devel sh -c "apt-get update && apt-get install -y python3 && python3 bin/runtests.py"
